### ISSUE TITLE
Style/TrailingCommaInArguments shouldn't care about heterogenous args

### ISSUE THREAD

**Issue by ptarjan** [rubocop-hq/rubocop#2847]
With this config:

```
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
```

We feel that both of these should be acceptable:

```
foo(
  a, b,
  c
)
```

and 

```
foo(
  a, b,
  c,
)
```

**Comment by faucct** [comment]
But this is not even valid ruby syntax.

**Comment by ptarjan** [comment]
@faucct fixed

**Comment by smakagon** [comment]
@ptarjan  @faucct @bbatsov  Seems like this issue has been fixed?
I couldn't reproduce it with current rubocop version:
```
rubocop -V
0.49.1 (using Parser 2.4.0.0, running on ruby 2.3.0 x86_64-darwin16)
```
Should we close this issue?

**Comment by Drenmi** [comment]
@smakagon: Looks like I can still reproduce this using the second example, and the configuration provided:

```ruby
# offense.rb
foo(
  a, b,
  c,
)
```

```yaml
# .rubocop.yml
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
```

```
Offenses:

offense.rb:3:4: C: Style/TrailingCommaInArguments: Avoid comma after the last parameter of a method call, unless each item is on its own line.
  c,
   ^
```

**Comment by smakagon** [comment]
@Drenmi thanks, good point. Yes, the second example is still reproducible. 
I wanted to go through existing issues and clean those a little bit. Because I'm sure we could reduce number of open issues.

**Comment by Drenmi** [comment]
> I wanted to go through existing issues and clean those a little bit. Because I'm sure we could reduce number of open issues.

Yes, and there are a lot of important additions and and low hanging fruit buried in the issues. 😊

**Comment by smakagon** [comment]
@ptarjan seems like there is a config option called `consistent_comma` which covers exact your case:
```
# good if EnforcedStyleForMultiline is consistent_comma
method(
  1, 2,
  3,
)

# good if EnforcedStyleForMultiline is comma or consistent_comma
method(
  1,
  2,
)
```
Let me know if that helps so we can close the issue.

**Comment by ptarjan** [comment]
If I remember correctly consistent_comma fails in other ways. Does it pass
both of my examples?

**Comment by smakagon** [comment]
Yes, with `consistent_comma` it would require you to to add comma at the end of last argument for this example:
```
foo(
  a, b,
  c
)
```
But it makes sense since it says `EnforcedStyleForMultiline`, so comma for multiline arguments is enforced. If you don't need it, you can use it with `no_comma` argument.

**Comment by ptarjan** [comment]
I think the general goal I had with this issue (sorry it has been a while
since I opened it) is that I'd like to enforce trailing commas when every
arg is on its own line, but once people start mixing single arg and multi
arg lines then I don't want to enforce it.

This condition comes up often with functions that take some positional args
and then an optional arg hash. Usually people put the positional args all
on one line and then the hash with each key and value on their own line. In
that case we don't want to force the trailing comma since the closing paren
will hug the ending and a comma just gets in the way.

**Comment by bbatsov** [comment]
There hasn't been much activity on this ticket and our Core Team is spread too thin on so many tasks, so I'll just close it for the sake of having a cleaner lists of tasks to focus on. We'd gladly review a PR, but it's unlikely that'd we're going to tackle this ourselves in the foreseeable future.
